language: ruby
cache: bundler
bundler_args: --without production

rvm:
 - 2.7.0
 
before_install:
 - gem install bundler:2.2.11

script:
 - curl -sL https://deb.nodesource.com/setup_10.x | bash -
 - bundle exec rspec